version: "3.8"

# https://speedscale.com/blog/mockserver-https-apis/
services:
  mockServer:
    container_name: 'mockServer'
    image: mockserver/mockserver:5.15.0
    command: -logLevel INFO
    ports:
      - 1080:1080
    volumes:
      - ./initializer.json:/config/initializer.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
    networks:
      - network-deb
    
  db:
    image: postgres:13
    restart: always
    container_name: 'db'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Compensations
    ports:
      - 11237:5432
    networks:
      - network-deb

  api:
    container_name: 'api'
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5283:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "MockForPullRequest"
    networks:
      - network-deb

  karate-tests:
    build:
      dockerfile: KarateDockerfile
      context: .
    depends_on:
      - api
    command: ["karate", "/karate"]
    volumes:
      - .:/karate
    networks:
      - network-deb

networks:
  network-deb: {}
