version: "3.8"

services:
  db:
    image: postgres:13
    profiles: ["MockForPullRequest", "MockForDevelopment"] # The database is required 
                                                           # to run the application from the IDE and 
                                                           # to run it from docker-compose completely
    restart: always
    container_name: 'db'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Compensations
    ports:
      - 11237:5432
    networks:
      - compensations-network

  mockserver: # Used for simulating external dependencies
    container_name: 'mockserver'
    image: mockserver/mockserver:5.15.0
    profiles: ["MockForPullRequest"]
    command: -logLevel INFO
    ports:
      - 1080:1080
    volumes:
      - ./initializer.json:/config/initializer.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializer.json
    networks:
      - compensations-network

  api:
    container_name: 'api'
    profiles: ["MockForPullRequest"]
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5283:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "MockForPullRequest"
    networks:
      - compensations-network

  local-karate-tests: # Karate-tests on local environment with mock-server
    container_name: 'local-karate-tests'
    # Use the template from the templates.yml file to avoid duplicate code
    extends:
            file: templates.yml
            service: karate-tests
    profiles: ["MockForPullRequest"]
    environment:
      AUTH_API_ROOT_URL: "http://mockserver:1080"
      API_ROOT_URL: "http://api"
      SHOULD_USE_FAKE_EXTERNAL_DEPENDENCIES: "true"
      AUTH_LOGIN: "any_login"
      AUTH_PASSWORD: "any_password"
    networks:
      - compensations-network
      
  production-karate-tests: # Karate-tests on production environment
    container_name: 'production-karate-tests'
    # Use the template from the templates.yml file to avoid duplicate code
    extends:
            file: templates.yml
            service: karate-tests
    profiles: ["ProdForDeployment"]
    environment:
      AUTH_API_ROOT_URL: "https://innercircle.tourmalinecore.com/api"
      API_ROOT_URL: "https://innercircle.tourmalinecore.com"
      SHOULD_USE_FAKE_EXTERNAL_DEPENDENCIES: "false"
      AUTH_LOGIN: ${AUTH_LOGIN}
      AUTH_PASSWORD: ${AUTH_PASSWORD}

networks:
  compensations-network: {} # Internal network for communication of containers of the same docker-compose
  ic-backend-deb: # An external network used to communicate containers from different docker-compose. 
                  # It must match the network name of another docker-compose and be created by a separate command 
                  # before launching all docker-compose
    external: true
