name: Karate Local Testing

on:
  push:
    branches:
      - 'feature/*' 
      
  pull_request:
    branches:
      - 'master'

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  test:
    # Image to run project and tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run service via docker-compose and run Karate-tests
      run: |
        LOGS=$(docker-compose --profile local-run up --abort-on-container-exit)
        FILTERED_LOGS=$(echo "$LOGS" | sed -E 's/"login":"[^"]*"/"login":"****"/g' \
                                 | sed -E 's/"password":"[^"]*"/"password":"****"/g' \
                                 | sed -E 's/"accessToken":[^,}]*"[^"]*"/"accessToken":"****"/g' \
                                 | sed -E 's/"Authorization":"[^"]*"/"Authorization":"****"/g' \
                                 | sed -E 's/"X-DEBUG-TOKEN":[^,}]*"[^"]*"/"X-DEBUG-TOKEN":"****"/g' \
                                 | sed -E 's/accessToken":\{[^}]*\}/accessToken":{"value":"****"}/g' \
                                 | sed -E 's/X-DEBUG-TOKEN: [^ ]*/X-DEBUG-TOKEN: ****/g') 
        echo "$FILTERED_LOGS"
        FAILED=$(echo "$FILTERED_LOGS" | grep -oP 'failed: *\K\d+')
        PASSED=$(echo "$FILTERED_LOGS" | grep -oP 'passed: *\K\d+')
        echo "Failed tests: $FAILED"
        echo "Passed tests: $PASSED"
        if [ "$FAILED" -gt 0 ]; then
          echo "Failed tests found! Failing the pipeline..."
          exit 1
        fi
        if [ "$PASSED" -eq 0 ]; then
          echo "No tests passed! Failing the pipeline..."
          exit 1
        fi

  production-test:
    # Image to run project and tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Compose environment variables
      run: |
        echo AUTH_LOGIN=${{ secrets.AUTH_LOGIN }} >> .env
        echo AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }} >> .env
    - name: Run service via docker-compose and run Karate-tests
      run: |
        LOGS=$(docker-compose --profile production-e2e-tests up --abort-on-container-exit)
        FILTERED_LOGS=$(echo "$LOGS" | sed -E 's/"login":"[^"]*"/"login":"****"/g' \
                                 | sed -E 's/"password":"[^"]*"/"password":"****"/g' \
                                 | sed -E 's/"accessToken":[^,}]*"[^"]*"/"accessToken":"****"/g' \
                                 | sed -E 's/"Authorization":"[^"]*"/"Authorization":"****"/g' \
                                 | sed -E 's/"X-DEBUG-TOKEN":[^,}]*"[^"]*"/"X-DEBUG-TOKEN":"****"/g' \
                                 | sed -E 's/accessToken":\{[^}]*\}/accessToken":{"value":"****"}/g' \
                                 | sed -E 's/X-DEBUG-TOKEN: [^ ]*/X-DEBUG-TOKEN: ****/g' \
                                 | sed -E 's/Authorization: [^ ]*/Authorization: ****/g')
        echo "$FILTERED_LOGS"
        FAILED=$(echo "$FILTERED_LOGS" | grep -oP 'failed: *\K\d+')
        PASSED=$(echo "$FILTERED_LOGS" | grep -oP 'passed: *\K\d+')
        echo "Failed tests: $FAILED"
        echo "Passed tests: $PASSED"
        if [ "$FAILED" -gt 0 ]; then
          echo "Failed tests found! Failing the pipeline..."
          exit 1
        fi
        if [ "$PASSED" -eq 0 ]; then
          echo "No tests passed! Failing the pipeline..."
          exit 1
        fi
