name: Run karate tests in isolation using local env

on:
  push:
    branches: [ feature/* ]

jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout local-env
        uses: actions/checkout@v4
        with:
          repository: TourmalineCore/inner-circle-local-env

      - name: Deploy Local Env to Kind k8s
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            kind create cluster --name inner-circle --config kind-local-config.yaml --kubeconfig ./.inner-circle-cluster-kubeconfig
            export KUBECONFIG=$(pwd)/.inner-circle-cluster-kubeconfig
            helmfile --environment local --namespace local -f deploy/helmfile.yaml apply
          push: never

      - name: Checkout api
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
        
      - name: Download Karate JAR
        run: |
          cd ..
          cd inner-circle-compensations-api/
          curl -L https://github.com/karatelabs/karate/releases/download/v1.5.1/karate-1.5.1.jar -o karate.jar

      - name: Run Karate Tests
        run: |
          java -jar karate.jar .
        env:
          AUTH_API_ROOT_URL: "http://localhost:40100"
          API_ROOT_URL: "http://localhost:40100"
          AUTH_LOGIN: "ceo@tourmalinecore.com"
          AUTH_PASSWORD: "cEoPa$$wo1d"

          