name: Run karate tests in isolation using local env

on:
  push:
    branches: [ feature/* ]

jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout local-env
        uses: actions/checkout@v4
        with:
          repository: TourmalineCore/inner-circle-local-env

      - name: Deploy Local Env to Kind k8s
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            kind create cluster --name inner-circle --config kind-local-config.yaml --kubeconfig ./.inner-circle-cluster-kubeconfig
            export KUBECONFIG=$(pwd)/.inner-circle-cluster-kubeconfig
            helmfile --environment local --namespace local -f deploy/helmfile.yaml apply
          push: never

      - name: Checkout api
        uses: actions/checkout@v4

      - name: Run Karate Tests
        run: |
            mvn test -Dkarate.options="classpath:"
        env:
          AUTH_API_ROOT_URL: "http://localhost:40100"
          API_ROOT_URL: "http://localhost:40100"
          AUTH_LOGIN: "test"
          AUTH_PASSWORD: "test"

          